name: skynet-typescript-dynamodb-plugin
description: Plugin that applies dynamoDB integration to a typescript lambda app
types:
  - app
inputs:
  - label: Input Example
    type: text
    name: example
    default: any text
  - label: Example of number
    type: int
    name: any_number
    default: "10"
  - label: Example of list
    type: multiselect
    name: any_list
    items:
      - item1
      - item2
