name: skynet-typescript-dynamodb-plugin
description: Plugin that applies dynamoDB integration to a typescript lambda app
types:
  - app
inputs:
  - label: DynamoDB Table Name
    type: text
    name: table_name
    default: Entity

hooks:
  - type: edit
    trigger: before-render
    path: infra/lib/{{service_name}}-service-stack.ts
    changes:
      - search:
          string: import * as cdk from "@aws-cdk/core"
          insert-after:
            snippet: snippets/typescript-dynamodb-plugin-import.txt
          when:
            not-exists: import { StackSpotDynamoDBTable } from "@stackspot/cdk-component-dynamodb-typescript"
  - type: edit
    trigger: before-render
    path: infra/lib/{{service_name}}-service-stack.ts
    changes:
      - search:
          string: "super(scope, id, props);"
          insert-after:
            snippet: snippets/typescript-dynamodb-plugin-constructor.txt
          when:
            not-exists: new StackSpotDynamoDBTable(this, "StackSpotDynamoDBTable"
  - type: edit
    trigger: before-render
    path: package.json
    changes:
      - search:
          string: "scripts"
          insert-after:
            snippet: snippets/package-json-scripts.txt
          when:
            not-exists: "source:setup:dynamodb"
  - type: run
    trigger: after-render
    mac:
      - npm run infra:install:dynamodb
      - npm run infra:format:fix
      - npm run infra:build:cdk
      - npm run source:setup:dynamodb
    linux:
      - npm run infra:install:dynamodb
      - npm run infra:format:fix
      - npm run infra:build:cdk
      - npm run source:setup:dynamodb
    windows:
      - npm.cmd run infra:install:dynamodb
      - npm.cmd run infra:format:fix
      - npm.cmd run infra:build:cdk
      - npm.cmd run source:setup:dynamodb

displayName: DynamoDB Plugin

category: Backend

compatibility:
  - NodeJS 14.x

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [ "Typescript", "DynamoDB" ]
